name: basic tests

on: [push, pull_request]

jobs:
  basictests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
    - name: Install pytest
      run: python3 -m pip install pytest
    - name: Install numpy
      run: python3 -m pip install numpy==1.22.2
    - name: Install numpypi
      run: python3 -m pip install git+https://github.com/adcroft/numpypi.git
    - name: Install netCDF4 dependencies
      run: sudo apt-get install libhdf5-serial-dev netcdf-bin libhdf5-dev libnetcf-dev
    - name: Install netCDF4
      run: python3 -m pip install netCDF4
    - name: ocean_grid_generator test
      run: pytest -v
